<!-- Generated by IcoMoon.io -->
<svg
	version="1.1"
	xmlns="http://www.w3.org/2000/svg"
	width="768"
	height="768"
	viewBox="0 0 768 768"
>
	<g id="icomoon-ignore"> </g>
	<path
		d="M190.6 430.6l-45.3-45.3-136 136c-12.5 12.5-12.5 32.8 0 45.3l136 136 45.3-45.3-81.3-81.3h466.7v-64h-466.7l81.3-81.4z"
	></path>
	<path
		d="M758.6 201.4l-136-136-45.3 45.3 81.4 81.4h-466.7v64h466.7l-81.4 81.4 45.3 45.3 136-136c12.5-12.7 12.5-32.9 0-45.4z"
	></path>
</svg>
