<!-- generated by icomoon.io - licensed Lindua icon -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 768 768" width="100%" height="100%">
<path d="M768 64h-576v64h256v576h64v-576h256z"></path>
<path d="M0 416h128v288h64v-288h128v-64h-320z"></path>
</svg>
