version: '3.9'

services:
  varnish:
    build:
      context: varnish
      dockerfile: Dockerfile
      args:
        HASS_HOST: 10.0.0.82
        FRONTEND_HOST: app
    ports:
      - '6081:6081'
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: '.env'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ORIGIN=http://localhost:3000
