---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: infra-map
  name: infra-map
  namespace: ${NAMESPACE}
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: infra-map
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: infra-map
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: infra-map
          envFrom:
            - secretRef:
                name: secret-env-values
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
