---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: infra-map
  name: infra-map
  namespace: ${NAMESPACE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infra-map
  template:
    metadata:
      labels:
        app: infra-map
    spec:
      containers:
        - image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: infra-map
          env:
          - name: HOMEASSISTANT_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret-env-values
                key: HOMEASSISTANT_TOKEN
          - name: HOMEASSISTANT_URL
            valueFrom:
              secretKeyRef:
                name: secret-env-values
                key: HOMEASSISTANT_URL
          - name: PROXMOX_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret-env-values
                key: PROXMOX_TOKEN
          - name: PROXMOX_URL
            valueFrom:
              secretKeyRef:
                name: secret-env-values
                key: PROXMOX_URL
          - name: TRAEFIK_URL
            valueFrom:
              secretKeyRef:
                name: secret-env-values
                key: TRAEFIK_URL
          resources:
            limits:
              cpu: 900m
              memory: 828Mi
            requests:
              cpu: 250m
              memory: 64Mi
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-login-secret
