---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infra-map
  name: infra-map-service
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: infra-map
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
